apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: pypi-server
  name: pypi-server
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pypi-server
  template:
    metadata:
      labels:
        name: pypi-server
    spec:
      securityContext:
        fsGroup: 9898
      volumes:
        - name: packages
          persistentVolumeClaim:
            claimName: pypi-server
      containers:
        - image: pypiserver/pypiserver:1.3.x
          name: pypi-server
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: packages
              mountPath: /data/packages

