apiVersion: v1
kind: Service
metadata:
  name: pypi-server
spec:
  selector:
    name: pypi-server
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pypi-server-db
spec:
  selector:
    name: pypi-server-db
  ports:
    - protocol: TCP
      port: 5432

